eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: microservicio-activo-empresarial
  data:
    mongodb:
      uri: mongodb+srv://joffre:joffre@bootcamp-microservicios.c9yhl.mongodb.net/activo-empresarial?retryWrites=true&w=majority
server:
  port: ${PORT:0}
